pipeline{
    agent any
    tools {
        maven 'Maven'
        jdk 'Java-11'
    }

    stages{
        stage('git checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/Ashwanthkulal/Ashwanth-kulal-P.git'
            }
        }

        stage('Maven clean'){
            steps{
                sh 'mvn clean'

            }
        }

        stage('Maven build'){
            steps{
                sh 'mvn clean install'
                
            }
        }
    }
}